const express = require("express")
const path = require("path")
const http = require("http")
const app = express()
const cors=require("cors")
require("dotenv").config()
const { routeInit } = require("./routes/route_config")
require("./db/mongoConnect")
app.use(cors())
app.use(express.json())
app.use(express.static(path.join(__dirname, "public")))
routeInit(app)
const server = http.createServer(app)
console.log("env",process.env.TEST,process.env.USER_DB)
let port = process.env.PORT || 3001
server.listen(port)

